name = "UAG Ketamine"
prefix = "UAG_Ketamine"
mainprefix = "z"

[version]
major = 0
minor = 0
patch = 0
git_hash = 8

[properties]
author = "UAG Development Team"
url = "https://github.com/uagpmc/arma3"

[hemtt.launch.default]
workshop = [
    "2369477168", # Advanced Developer Tools Workshop ID
]

[hemtt.launch.ace]
extends = "default"
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
]
